# .env
# RASA_X_VERSION=0.23.5
# RASA_SDK_VERSION=1.5.1
# docker-compose build
# docker-compose up -d
version: "3.4"

services:
  duckling:
    restart: always
    image: "rasa/duckling:latest"
    ports:
      - "8000:8000"
    command: ["duckling-example-exe", "--no-access-log", "--no-error-log"]
