name: Build Action Image
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image Tag'
        required: true
        default: 'latest'
      sdk-vers:
        description: 'Rasa SDK version?'
        required: true
        default: '2.1.2'
  push:
    paths:
    - 'actions/**'
#    - '.github/workflows/build-action-image.yml'

jobs:
  build-image:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest

    env:
      RASA_SDK_VERS: 2.1.2
      DOCKER_IMAGE_TAG: ${{ github.event.inputs.image-tag }}
      DOCKERHUB_USERNAME: stephens
      DOCKER_IMAGE_NAME: stephens/jokebot
      REQUIREMENTS_FILE: 'actions/requirements.txt'

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2

      - name: Build Actions Server Image
        uses: RasaHQ/rasa-action-server-gha@master
        with:
          actions_directory: 'actions'
          requirements_file: ${{ env.REQUIREMENTS_FILE }}
          docker_registry_login: ${{ env.DOCKERHUB_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          docker_image_tag: ${{ env.DOCKER_IMAGE_TAG }}
          rasa_sdk_version: ${{ env.RASA_SDK_VERS }}

  manual-build-image:
    name: Manually Build Action Server Docker Image
    if: ${{ github.event.inputs.why }}
    runs-on: ubuntu-latest

    env:
      RASA_SDK_VERS: ${{ github.event.inputs.sdk-version }}
      DOCKER_IMAGE_TAG: ${{ github.event.inputs.image-tag }}
      DOCKERHUB_USERNAME: stephens
      DOCKER_IMAGE_NAME: rgstephens/jokebot
      REQUIREMENTS_FILE: 'actions/requirements.txt'

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2
      - name: Build Actions Server Image
        uses: RasaHQ/rasa-action-server-gha@master
        with:
          actions_directory: 'actions'
          requirements_file: ${{ env.REQUIREMENTS_FILE }}
          docker_registry_login: ${{ env.DOCKERHUB_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          docker_image_tag: ${{ env.DOCKER_IMAGE_TAG }}
          rasa_sdk_version: ${{ env.RASA_SDK_VERS }}