name: Continuous Integration
#on: [push]
on:
  push:
    paths:
    - 'actions/**'

jobs:
  docker:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest

    env:
      RASA_SDK_VERS: 2.1.2
      DOCKERHUB_USERNAME: stephens
      DOCKER_IMAGE_NAME: stephens/jokebot
      REQUIREMENTS_FILE: 'actions/requirements.txt'

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry 🔢
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin || true

      - name: Pull latest${{ matrix.image.tag_ext }} Docker image for caching
        run: docker pull ${{env.DOCKER_IMAGE_NAME}}:latest || true

      - name: Build latest${{ matrix.image.tag_ext }} Docker image
        run: docker build . --tag ${{env.DOCKER_IMAGE_NAME}}:latest --cache-from ${{env.DOCKER_IMAGE_NAME}}:latest

      - name: Push image with latest tag 📦
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker push ${{env.DOCKER_IMAGE_NAME}}:latest         
      - name: Build Actions Server Image
        uses: RasaHQ/rasa-action-server-gha@master
        with:
          actions_directory: 'actions'
          requirements_file: ${{ env.REQUIREMENTS_FILE }}
          docker_registry_login: ${{ env.DOCKERHUB_USERNAME }}
          docker_registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          docker_image_tag: 'latest'
          rasa_sdk_version: ${{ env.RASA_SDK_VERS }}